// Code generated by mockery v2.32.4. DO NOT EDIT.

package ec2

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// ChangeStatus provides a mock function with given fields: ctx, to, tagKey, tagValue
func (_m *MockInterface) ChangeStatus(ctx context.Context, to int, tagKey string, tagValue string) error {
	ret := _m.Called(ctx, to, tagKey, tagValue)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = rf(ctx, to, tagKey, tagValue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInterface_ChangeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeStatus'
type MockInterface_ChangeStatus_Call struct {
	*mock.Call
}

// ChangeStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - to int
//   - tagKey string
//   - tagValue string
func (_e *MockInterface_Expecter) ChangeStatus(ctx interface{}, to interface{}, tagKey interface{}, tagValue interface{}) *MockInterface_ChangeStatus_Call {
	return &MockInterface_ChangeStatus_Call{Call: _e.mock.On("ChangeStatus", ctx, to, tagKey, tagValue)}
}

func (_c *MockInterface_ChangeStatus_Call) Run(run func(ctx context.Context, to int, tagKey string, tagValue string)) *MockInterface_ChangeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockInterface_ChangeStatus_Call) Return(err error) *MockInterface_ChangeStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_ChangeStatus_Call) RunAndReturn(run func(context.Context, int, string, string) error) *MockInterface_ChangeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
